" Plugins to install using vim-plug
silent! call plug#begin('~/.vim/plugged')

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'dart-lang/dart-vim-plugin'
Plug 'junegunn/fzf.vim'
Plug 'udalov/kotlin-vim'
Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'rust-lang/rust.vim'
Plug 'godlygeek/tabular'
Plug 'vim-scripts/tlib'
Plug 'tomtom/tlib_vim'
Plug 'leafgarland/typescript-vim'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'flazz/vim-colorschemes'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'fatih/vim-go'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-repeat'
Plug 'garbas/vim-snipmate'
Plug 'tpope/vim-surround'
Plug 'posva/vim-vue'
Plug 'junegunn/vim-easy-align'
Plug 'dag/vim-fish'
Plug 'LnL7/vim-nix'

call plug#end()

" A must
syntax on
syntax sync fromstart
filetype off
filetype plugin on

set encoding=utf-8
setglobal fileencoding=utf-8

set autoread
set wildmenu
set noequalalways
set noshowmode
set ttyfast
set path+=**
set display+=lastline
set backspace=indent,eol,start

set ignorecase
set smartcase
set incsearch

set mousefocus
set mouse=a

set number
set expandtab
set autoindent
set tabstop=4
set shiftwidth=4

set guioptions=
set guicursor=a:block-Cursor
set guifont=Hack:h14
autocmd! GUIEnter * set vb t_vb=

colorscheme bee

set laststatus=2

autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

let mapleader="\<Space>"

vnoremap < <gv
vnoremap > >gv

nnoremap q: :q

nnoremap <silent> <Tab>  :tabnext<CR>
nnoremap <silent> <S-Tab>  :tabprev<CR>

nnoremap <silent> <Tab>  :tabnext<CR>
nnoremap <silent> <S-Tab>  :tabprev<CR>

nnoremap <silent> <leader>ve :vs $MYVIMRC<CR>
nnoremap <silent> <leader>vs :source $MYVIMRC<CR>

nnoremap <silent> <leader>s :sh<CR>

" -------- "
" NERDTree "
" -------- "

nnoremap <silent> <leader>t :NERDTreeToggle<CR>

" ---- "
" Rust "
" ---- "

let g:autofmt_autosave = 1
let g:rustfmt_autosave = 1

" ---------- "
" Commentary "
" ---------- "

autocmd FileType c setlocal commentstring=//\ %s
autocmd FileType vim setlocal commentstring=\"\ %s
autocmd FileType sql setlocal commentstring=--\ %s
autocmd FileType py setlocal commentstring=#\ %s
autocmd FileType swift setlocal commentstring=//\ %s
autocmd FileType vue setlocal commentstring=/*\ %s\ */
autocmd FileType cfg setlocal commentstring=#\ %s
autocmd FileType dosini setlocal commentstring=;\ %s

" --- "
" FZF "
" --- "

set rtp+=~/.fzf
nnoremap <leader>o :Buffers<CR>

" ---------- "
" Easy Align "
" ---------- "

xmap ga <Plug>(EasyAlign)

autocmd BufRead *.rs :setlocal tags=./rusty-tags.vi;/,$RUST_SRC_PATH/rusty-tags.vi
autocmd BufWritePost *.rs :silent! exec "!rusty-tags vi --quiet --start-dir=" . expand('%:p:h') . "&" | redraw!
