" A must
syntax on
filetype plugin indent on

" Fix syntax highlighting
" syntax sync fromstart

" Auto read and update files if edited by another program
set autoread

" Necessary for backspace to workin insert mode on all characters
set backspace=indent,eol,start

" Set path to recursively search when using the :find command
set path+=**

" Show horizontal list of values from the :find command
set wildmenu

" Disable auto comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Show as much of the last line as you can
set display+=lastline

" To view hidden characters
" set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
" set list 
" Change timeout in normal mode
" set timeoutlen=250

" Do not change window sizez upon opening/closing splits
set noequalalways

" Setting dictionary
set dict+=/usr/share/dict/cracklib-small

" Statusline
set laststatus=2
set statusline=%f
set statusline+=[%c:%l/%L]
" set statusline+=%=%{FugitiveStatusline()}\ [%c:%l/%L]

" Color Scheme
colorscheme bee

" Auto read and update files if edited by another program
set autoread

" Necessary for backspace to workin insert mode on all characters
set backspace=indent,eol,start

" Set path to recursively search when using the :find command
set path+=**

" Disable auto comment insertion
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Set cursor to be in middle of screen and highlight
" set so=999
" set cursorline

" Used to make rendering faster when multiple windows are open
set ttyfast

" Vim-Latex-Live-Preview Variable
" let g:livepreview_previewer = 'mupdf'

" Basic better of life settings
set number
" set relativenumber 
" Show as much of the last line as you can
set display+=lastline

" To view hidden characters
" set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
" set list 

" Do not change window sizez upon opening/closing splits
set noequalalways

" Setting dictionary
set dict+=/usr/share/dict/cracklib-small

" Color Scheme
colorscheme bee

" Used to make rendering faster when multiple windows are open
set ttyfast

" Vim-Latex-Live-Preview Variable
" let g:livepreview_previewer = 'mupdf'

" ---------------- "
" Editor Settings "
" ---------------- "

set number

set tabstop=4
set expandtab
set shiftwidth=4
set expandtab
" set autoindent
" set smartindent
set smartcase

" Folding options
set foldenable
set foldmethod=syntax

" Incremental Search
set incsearch

" Basic mouse settings

" Mouse will select only what visual mode coud select in current window
set mouse=a
set mousefocus

set autoindent
set smartindent
set cindent

" --------------- "
" Search Settings "
" --------------- "

set smartcase
set incsearch

" ------------- "
" Fold Settings "
" ------------- "
set foldenable
set foldmethod=syntax
set foldlevel=99

" ------------------- "
" StatusLine Settings "
" ------------------- "

set laststatus=2
set statusline=%f
set statusline+=[%c:%l/%L]
set statusline+=%=%{FugitiveStatusline()}\ [%c:%l/%L]

set wildmenu

" -------------- "
" Mouse Settings "
" -------------- "

set mouse=a
set mousefocus

" -------- "
" Mappings "
" -------- "

" No more command windows!
nnoremap q: :q

" Easy tab movement
nnoremap <silent> <Tab>  :tabnext<CR>
nnoremap <silent> <S-Tab>  :tabprev<CR>

" --------------- "
" Leader Mappings "
" --------------- "

let mapleader="\<Space>"

" Dont want to press shift all the time because keyboard is hard to type on
" nnoremap ; :

" Open buffer list
" nnoremap <silent> <leader>ls :ls<CR>

" Viewing and editting vimrc mappings
nnoremap <silent> <leader>ve :vs $MYVIMRC<CR>
nnoremap <silent> <leader>vs :source $MYVIMRC<CR>

" Open file explorer
" Editting and Sourcing vimrc
nnoremap <silent> <leader>ve :vs $MYVIMRC<CR>
nnoremap <silent> <leader>vs :source $MYVIMRC<CR>

" Open file explorer in current window
nnoremap <silent> <leader>t :Ex<CR>

" Suspend vim and open terminal
nnoremap <silent> <leader>s :sh<CR>

" Mapping for ctags
" nnoremap <leader>l <C-]>
" nnoremap <leader>h <C-O>

" Change fold bindings
" nnoremap <leader>fo zo
" nnoremap <leader>fc zc
" nnoremap <leader>fa za
" nnoremap R zR
" nnoremap M zM

" autocmd VimLeave * :mks!

" UTF-8 Support
" set encoding=UTF-8
" set fileencoding=UTF-8

" Changes primary key to use to change terminal from running mode
" to terminal mode
" set termwinkey=<C-w>

" No more command windows!
nnoremap q: :q

" -------------- "
" Netrw Settings "
" -------------- "

" Netrw settings
let g:netrw_liststyle=3
" let g:netrw_banner=0
" let g:netrw_winsize=15
let g:netrw_fastbrowse=2

" ------------------ "
" End Netrw Settings "
" ------------------ "

" ----------------- "
" Rust-vim Settings "
" ----------------- "

let g:autofmt_autosave = 1

" -------------- "
" Netrw Settings "
" -------------- "

let g:netrw_liststyle=3
let g:netrw_fastbrowse=2

" ------------------- "
" Commentary Settings "
" ------------------- "

" Setting Tim Pope's commentary variable
autocmd FileType c setlocal commentstring=//\ %s
autocmd FileType vim setlocal commentstring=\"\ %s
autocmd FileType sql setlocal commentstring=--\ %s
autocmd FileType py setlocal commentstring=#\ %s
autocmd FileType swift setlocal commentstring=//\ %s
autocmd FileType vue setlocal commentstring=/*\ %s\ */
autocmd FileType cfg setlocal commentstring=#\ %s

" ----------------------- "
" End Commentary Settings "
" ----------------------- "

" ------------ "
" Tab Settings "
" ------------ "

source ~/.vim/tabs.vim

" Tab status line
set tabline=%!MyTabLine()
set showtabline=2

" Tab commands
nnoremap <silent> th  :tabfirst<CR>
nnoremap <silent> tk  :tabnext<CR>
nnoremap <silent> tj  :tabprev<CR>
nnoremap <silent> tl  :tablast<CR>
nnoremap <silent> tt  :tabfind<Space>
nnoremap <silent> tn  :tabnext<Space>
nnoremap <silent> tm  :tabm<Space>
nnoremap <silent> td  :tabclose<CR>

nnoremap <silent> <Tab>  :tabnext<CR>
nnoremap <silent> <S-Tab>  :tabprev<CR>

" ---------------- "
" End Tab Settings "
" ---------------- "

" --------------------- "
" Start of GUI Settings "
" --------------------- "
" TabLine functions
source ~/.vim/tabs.vim

" TabLine
set tabline=%!MyTabLine()
set showtabline=2

" ------------ "
" GUI Settings "
" ------------ "

" No scroll/menu bars
set guioptions=
autocmd! GUIEnter * set vb t_vb=

" Set gui font
set guifont=Hack:h14

" Set cursor to block for everything
set guicursor=a:block-Cursor

" ------------------- "
" End of GUI Settings "
" ------------------- "
set guifont=Hack:h14
set guicursor=a:block-Cursor

" ------------ "
" FZF Settings "
" ------------ "

set rtp+=~/.fzf
nnoremap <leader>o :Buffers<CR>
