# History
autoload -Uz compinit && compinit -i
HISTSIZE=500
SAVEHIST=500
HISTFILE="$HOME/.zsh_history"

# colors
autoload -U colors && colors

autoload -Uz vcs_info
zstyle ':vcs_info:git:*' formats ' %b'
    
# Declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[path]='none'
ZSH_HIGHLIGHT_STYLES[alias]='fg=119'

# Prompt customization
precmd() {
    colors
    vcs_info
    PROMPT="%{$fg[cyan]%}%~%{$fg[yellow]%}${vcs_info_msg_0_}%{$fg[green]%} $%{$reset_color%} "
}

# turn on colors for ls command
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# autoload -U promptinit; promptinit

# Suggest command from history that fits 
source ~/Config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Zsh Syntax Highlighting
source ~/Config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias cc="cargo check"
alias vims="vim -S Session.vim"
alias ls="ls --color=auto"
alias la="ls -a"
alias ll="ls -l"

# Git
alias gs="git status"
alias gp="git pull"
alias ga="git add -A"
alias gc="git commit -m "

# add rust to the path
export PATH="$HOME/.cargo/bin":$PATH
export PATH="$HOME/rust-ctags":$PATH

# Short error format for rust
# export RUSTFLAGS="--error-format=short"

# Movement keys
bindkey '^l' forward-char
# bindkey '^h' backward-char

bindkey '^w' forward-word
bindkey '^b' backward-delete-word

# bindkey '^ ' autosuggest-accept
# bindkey '\t' autosuggest-accept

# _fzf_compgen_path() {
#   fd --hidden --follow --exclude ".git" . "$1"
# }

# Use fd to generate the list for directory completion
# _fzf_compgen_dir() {
#   fd --type d --hidden --follow --exclude ".git" . "$1"
# }

# Use fd directly
export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git --color=always'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Define a `preview` command
alias preview="fzf --preview 'bat --color \"always\" {}' | xargs vim"

# Default options
export FZF_DEFAULT_OPTS="--ansi --prompt '❯ ' --inline-info --layout reverse --height 50%"

# GOPATH
export GOPATH=~/go

export PATH=$PATH:$GOPATH/bin
