# Vim mode on escape
bindkey -v

# History
autoload -Uz compinit && compinit -i
HISTSIZE=500
SAVEHIST=500
HISTFILE="$HOME/.zsh_history"

# colors
autoload -U colors && colors

autoload -Uz vcs_info
zstyle ':vcs_info:git:*' formats ' %b'
    
# Declare the variable
typeset -A ZSH_HIGHLIGHT_STYLES

ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[path]='none'
ZSH_HIGHLIGHT_STYLES[alias]='fg=119'

# Prompt customization
precmd() {
    vcs_info
    PROMPT="%{$fg[cyan]%}%~%{$fg[yellow]%}${vcs_info_msg_0_}%{$fg[green]%}$(vim_open) $%{$reset_color%} "
}


autoload -U promptinit; promptinit

# Suggest command from history that fits 
source ~/Config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# Zsh Syntax Highlighting
source ~/Config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Movement keys
bindkey '^l' forward-char

bindkey '^w' forward-word
bindkey '^b' backward-delete-word

bindkey '^ ' autosuggest-accept

alias vims="vim -S Session.vim"
alias ls="exa"
alias la="ls -a"
alias ll="ls -l"

# Git
alias gs="git status"
alias gp="git pull"
alias ga="git add -A"
alias gc="git commit -m"
alias gd="git diff"

alias pings="ping 8.8.8.8"
alias up="cd .."

alias cmt="cargo make test"
alias cm="cargo make"
alias cc="cargo check"

export EDITOR=vim

# Custom scripts to path
export PATH=$PATH:$HOME/.config/scripts
# Flutter
export PATH=$PATH:$HOME/flutter/bin

# NVM
export NVM_DIR='/Users/danielakhterov/.nvm'

[[ -s "/home/daniel/.sdkman/bin/sdkman-init.sh" ]] && source "/home/daniel/.sdkman/bin/sdkman-init.sh"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

function vim_open() {
    if [[ $(env | grep "VIMRUNTIME=*" | wc -l) -ge 1 ]]; then
        echo " vim"
    else
        echo ""
    fi
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/daniel/.sdkman"
